# Generated by Django 5.2.8 on 2025-11-13 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_alter_inspection_checklist_and_more'),
        ('users', '0004_alter_appuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_actions', to='users.appuser')),
                ('inspection_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='inspections.inspectionitem')),
            ],
            options={
                'verbose_name': 'Corrective Action',
                'verbose_name_plural': 'Corrective Actions',
            },
        ),
    ]
