# Generated by Django 5.2.8 on 2025-11-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_correctiveaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctiveaction',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('AWAITING_REINSPECTION', 'Awaiting Reinspection'), ('REINSPECTED', 'Reinspected')], default='OPEN', max_length=50),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PASSED', 'Passed')], default='PENDING', max_length=50),
        ),
    ]
