# Generated by Django 5.2.8 on 2025-11-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_alter_correctiveaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionitem',
            name='passed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
