# Generated by Django 5.2.8 on 2025-11-09 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_appuser_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
