# Generated by Django 5.2.8 on 2025-11-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('users', '0004_alter_appuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Assign users (admins, inspectors, kitchen staff) to this school.', related_name='schools', to='users.appuser'),
        ),
    ]
