# Generated by Django 5.2.8 on 2025-11-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_users'),
        ('users', '0004_alter_appuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name'], 'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='school',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='school',
            name='users',
        ),
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='kitchen_staff',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'KITCHEN'}, related_name='kitchen_schools', to='users.appuser'),
        ),
        migrations.AddField(
            model_name='school',
            name='managers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'MANAGER'}, related_name='managed_schools', to='users.appuser'),
        ),
        migrations.AddField(
            model_name='school',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
