# Generated by Django 5.2.8 on 2025-11-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_school_options_remove_school_is_active_and_more'),
        ('users', '0004_alter_appuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='inspectors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'INSPECTOR'}, related_name='inspection_schools', to='users.appuser'),
        ),
    ]
